[package]
name = "vimscript-lint"
version = "0.1.0"
authors = ["Tomasz Zurkowski <tomasz.zurkowski@gmail.com>"]
edition = "2018"

[dependencies]
vimscript-core = { path = "../vimscript-core" }
serde_json = "1.0"
syntax = { path = "../syntax" }
