[package]
name = "syntax"
version = "0.1.0"
authors = ["Tomasz Zurkowski <zurkowski@google.com>"]
edition = "2018"

[dev-dependencies]
expect-test = "1.0.1"

[dependencies]
rowan = "0.10.0"
parser = { path = "../parser" }
vimscript-core = { path = "../vimscript-core" }
